import './js/contact-us.js';
import './js/follow.js';
import './js/mobile-menu.js';
import './js/slick.js';
import './js/modal.js';
import './js/form-validation';
import './js/header-scroll';
import './js/anchor-scroll';
import './js/simplelightbox';
